networks:
  vpn-bot:
    external: true

services:
  telegram_bot:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: telegram_bot
    environment:
      TZ: Europe/Moscow
    env_file:
      - env/.env
    networks:
      - vpn-bot
    ports:
      - "8080:8080"
    command: ["python", "-m", "src"]
