networks:
  vpn-network:
    external: true

services:
  telegram_bot:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: telegram_bot
    environment:
      TZ: Europe/Moscow
    env_file:
      - env/.env
    networks:
      - vpn-network
    ports:
      - "8080:8080"
    command: ["python", "main.py"]

volumes:
  postgres_data: